#!/usr/bin/env bash
# This script copies a file in the home directory of a server

if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
scp -o StrictHostKeyChecking=off -i "$4" "$1" "$3"@"$2":~/
