#!/usr/bin/env bash
# This script installs nginx and configures it

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo nginx -s reload
