#!/usr/bin/env bash
# This script configures a ubuntu server

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
