#!/usr/bin/env bash
# This script configures a ubuntu server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
