#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely

pid="$$"
file="/var/run/myscript.pid"

echo "$pid" > "$file"

trap 'echo "Y U no love me?!"; exit 0' SIGINT
trap 'echo "I hate the kill command"; rm "$file"; exit 0' SIGTERM
trap 'rm "$file"; exit 0' SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
