#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
#	and displays "I am invincible!!!" when receiving a SIFTERM signal
sig_term_trap() {
	echo "I am invincible!!!"
}

trap 'sig_term_trap' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
