#!/usr/bin/env bash
# This script configures an Ubuntu server
cp /etc/hosts ~/hosts.origin
echo "8.8.8.8 facebook.com" >> ~/hosts.origin
sed -i "s/"127.0.0.1"/"127.0.0.2"/g" ~/hosts.origin
cp -f ~/hosts.origin /etc/hosts
