#!/usr/bin/env bash
# This script configures an Ubuntu server
cp /etc/hosts ~/hosts.origin
echo "127.0.0.2 localhost" > ~/hosts.origin
echo "8.8.8.8 facebook.com" >> ~/hosts.origin
cp -f ~/hosts.origin /etc/hosts
